name: "SSTP VPN Client"
version: "1.0.3"
slug: "sstp_client"
description: "SSTP VPN client for Home Assistant"
arch:
  - aarch64
  - amd64
startup: services
boot: auto
host_network: true
init: false

privileged:
  - NET_ADMIN
devices:
  - /dev/ppp

options:
  server: ""
  username: ""
  password: ""
schema:
  server: str
  username: str
  password: password

